---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: about
  label: About
  create: documents
  match: "**/*"
  templates:
  - about
- type: directory
  path: conference
  label: Conference
  create: all
  match: "**/*"
  templates:
  - conference
- type: directory
  path: teams
  label: Teams
  create: documents
  match: "**/*"
  templates:
  - teams
upload_dir: ''
public_path: https://res.cloudinary.com/dr6b9c9ko/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: "/build"
  install_dependencies_command: pnpm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: pnpm start
