---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: about
  label: about
  create: documents
  match: "**/*"
- type: directory
  path: conference
  label: Conference
  create: all
  match: "**/*"
- type: directory
  path: teams
  label: Teams
  create: documents
  match: "**/*"
upload_dir: static/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/build"
  install_dependencies_command: pnpm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: pnpm start
